
service: myServerlessProject444

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:*
      Resource: '*'

custom:
  tableName: myDynamoDBTable 

functions:
  analyse:
    handler: lambdas/endpoints/analyse.handler
    events:
      - http:
          path: analyse/{id}
          method: POST
          cors: true
      
      
     