
service: myserverlessproject

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
    signupTableName: ${self:custom.signupTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - ses:*
      Resource: '*'
  apiGateway:
    apiKeys:
      - name: MyFreeApiKey
        value: Lc9XtRmZ8OaJzKvS2q0F
      - name: MyPaidApiKey
        value: hY4sDpGnT3iXbM6oWfEj

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
          private: true
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - http:
          path: get-player-score/{ID}
          method: GET
          cors: true
  createPlayerScore:
    handler: lambdas/endpoints/createPlayerScore.handler
    events:
      - http:
          path: create-player-score/{ID}
          method: post
          cors: true
  UpdatePlayerScore:
    handler: lambdas/endpoints/updatePlayersScores.handler
    events:
      - http:
          path: update-player-score/{ID}
          method: PUT
          cors: true
  getGameScores:
    handler: lambdas/endpoints/getGameScores.handler
    events:
      - http:
          path: get-game-score/{game}
          method: GET
          cors: true
  createFile:
    handler: lambdas/endpoints/createFile.handler
    events:
      - http:
          path: create-file/{fileName}
          method: POST
          cors: true
  getFile:
    handler: lambdas/endpoints/getFile.handler
    events:
      - http:
          path: get-file/{fileName}
          method: GET
          cors: true
  pproxy:
    handler: lambdas/endpoints/proxy.handler
    events:
      - http:
          path: chuck-norris/{proxy+}
          method: ANY
          integration: lambda-proxy
          request:
            parameters:
              paths:
                proxy: true
  sendEmail:
    handler: lambdas/endpoints/sendEmail.handler
    events:
      - http:
          path: send-email
          method: POST
          cors: true
  addSignup:
    handler: lambdas/stepFunctionsLambdas/addSignup.handler
  getSignup:
    handler: lambdas/stepFunctionsLambdas/getSignup.handler
  sendReminderEmail:
    handler: lambdas/stepFunctionsLambdas/sendReminderEmail.handler

      


      
      

plugins:
  - serverless-s3-sync
  - serverless-webpack
  - serverless-step-functions

package:
  individually: true

custom:
  tableName: player-points
  signupTableName: signup-table-name
  bucketName: jaimebucketjdewdiwjsiwjsjwisjwi
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: UploadData


stepFunctions:
  validate: true
  stateMachines:
    reminderEmail:
      name: reminderEmail
      eventes:
        - http:
            path: sign-with-reminders
            method: post
            cors: true
      definition: ${file(./stepFunction.yml)}


resources:
  Resources:
    DemoBucke: 
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: game
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

        GlobalSecondaryIndexes:
          - IndexName: game-index
            KeySchema:
              - AttributeName: game
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    MyEmailSignupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.signupTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
                
    myAssumeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: MyAssumeRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com  
              Action:
                - sts:AssumeRole

