
service: myServerlessProject444

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
        - comprehend:*
      Resource: '*'

custom:
  tableName: myDynamoDBTable 

functions:
  sendReminder:
    handler: lambdas/scheduleTasks/reminderEmail.handler
    events:
      - schedule: cron(0 9 ? * 7 *)
  sendMorningNews:
    handler: lambdas/scheduleTasks/morningNew.handler
    events:
      - schedule: cron(15 7 ? * * *)
      
      
     