
service: myServerlessProject444

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:SetSMSAttributes
        - sns:Publish
      Resource: '*'

custom:
  tableName: myDynamoDBTable 

functions:
  sendSMS:
    handler: lambdas/endpoints/sendSMS.handler
    events:
      - http:
          path: send-sms
          method: POST
          cors: true
      
     