
service: myServerlessProject444

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    tableName: ${self.custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  tableName: myDynamoDBTable 

functions:
  webSocketconnect:
    handler: lambdas/websocktes/connect.handler
    events:
      - websocket:
          route: $connect
  webSocketdisconnect:
    handler: lambdas/websocktes/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  webSocketdefault:
    handler: lambdas/websocktes/default.handler
    events:
      - websocket:
          route: $default
  webSocketmessage:
    handler: lambdas/websocktes/message.handler
    events:
      - websocket:
          route: message

resources:
  Resources:
    webSocketUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self.custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
      
     